--CREATE USER IF NOT EXISTS SA SALT 'decc4df4e58f5cd5' HASH '42c8eac10f2aba8c4666ec747038c16e8250018060264f0f128c881c9b66ed36' ADMIN;
CREATE TABLE IF NOT EXISTS JIRA_PROJECT(
   ID BIGINT IDENTITY PRIMARY KEY,
   NAME VARCHAR(255),
   PROJECT_ID BIGINT
);
--ALTER TABLE JIRA_PROJECT ADD CONSTRAINT CONSTRAINT_3 PRIMARY KEY(ID);
CREATE TABLE IF NOT EXISTS JIRA_USER (
    ID BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(255),
    USER_ID BIGINT
);      
CREATE TABLE IF NOT EXISTS PROJECT(
    ID BIGINT IDENTITY PRIMARY KEY,
    DESCRIPTION VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    NAME VARCHAR(255)
);    
CREATE TABLE IF NOT EXISTS USER_NAME(
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    USER_ID BIGINT
);          
CREATE TABLE IF NOT EXISTS PROJECT_USERS(
    PROJECT_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL
);           
CREATE TABLE IF NOT EXISTS USER(
    ID BIGINT IDENTITY PRIMARY KEY,
    EMAIL VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    LAST_NAME VARCHAR(255)
);        
CREATE TABLE IF NOT EXISTS USER_ROLES(
    USER_ID BIGINT NOT NULL,
    ROLE VARCHAR(255)
);       
    
CREATE TABLE IF NOT EXISTS WORK_LOG(
    ID BIGINT IDENTITY PRIMARY KEY,
    DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(255),
    HOURS DOUBLE NOT NULL,
    TOPIC VARCHAR(255),
    PROJECT_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL
);
ALTER TABLE JIRA_PROJECT ADD CONSTRAINT UK_G3KKV8PDPA78BNXY3EVDK0EUL UNIQUE(NAME);
ALTER TABLE USER ADD CONSTRAINT UK_OB8KQYQQGMEFL0ACO34AKDTPE UNIQUE(EMAIL);           
ALTER TABLE JIRA_USER ADD CONSTRAINT UK_88PUG0K733ILO2RENVIO8FGMR UNIQUE(NAME);       
ALTER TABLE USER_ROLES ADD CONSTRAINT FK55ITPPKW3I07DO3H7QOCLQD4K FOREIGN KEY(USER_ID) REFERENCES USER(ID) NOCHECK;      
ALTER TABLE JIRA_PROJECT ADD CONSTRAINT FK3SLMEJTG6Y3097I41XGPUWUW9 FOREIGN KEY(PROJECT_ID) REFERENCES PROJECT(ID) NOCHECK;              
ALTER TABLE PROJECT_USERS ADD CONSTRAINT FK9AT0EI37RLS7VD2M6SH92668H FOREIGN KEY(PROJECT_ID) REFERENCES PROJECT(ID) NOCHECK;             
ALTER TABLE PROJECT_USERS ADD CONSTRAINT FKSWC4G4H18LBXSL9OBVO97LNBL FOREIGN KEY(USER_ID) REFERENCES USER(ID) NOCHECK;   
ALTER TABLE WORK_LOG ADD CONSTRAINT FKHLTJHXEJF2FOYK78SDFN4H63C FOREIGN KEY(PROJECT_ID) REFERENCES PROJECT(ID) NOCHECK;  
ALTER TABLE WORK_LOG ADD CONSTRAINT FK2L5J2UBNTSMQ2TIND0QQ1AR71 FOREIGN KEY(USER_ID) REFERENCES USER(ID) NOCHECK;        
ALTER TABLE JIRA_USER ADD CONSTRAINT FKEECKLICBPETK2R68XNAHMNEEC FOREIGN KEY(USER_ID) REFERENCES USER(ID) NOCHECK;       
--INSERT INTO JIRA_USER VALUES(1, 'AI', 1);